{
    'name': "Homologación de Productos",
    'summary': "Tabla de equivalencias entre SKUs de clientes y productos internos",
    'author': "Tierranube",
    'website': "http://www.tierranube.cl",
    'category': 'Sales',
    'version': '18.0.0.1',
    'depends': ['base', 'sale', 'product', 'contacts', 'crm', 'sale_crm'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_partner_views.xml',
        'views/product_homologation_views.xml',
        'views/product_homologation_phase3_views.xml',
        'views/product_homologation_quote_views.xml',
        'views/product_homologation_rule_views.xml',
        'views/homologation_import_wizard_views.xml',
        'views/product_homologation_menu.xml',
        'views/crm_lead_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
